### ISSUE TITLE
Corruption & Async

### ISSUE THREAD

**Issue by rknell** [Belphemur/node-json-db#4]
Hello,

I have rolled my own system similar to this and am having trouble with corruption of the data when the app closes suddenly (or exits)

Just wondering if the Sync calls you make to the file system are sync because that solves that problem, and then by extension, why are they sync calls instead of Async? I would think that might hurt performance or is there a reason?

I know the answer is "Just try it out" but shoehorning your library in now would take a fair while, and it might not solve anything so I figure its worth a shot asking!

Kind regards,

Ryan

**Comment by Belphemur** [comment]
Hello @rknell,

Well I chose Sync I/O for multiple reason. I didn't want to juggle with different Promise when doing a push + save on disk. I discover that with the Async IO if not used properly with callback or Promise you corrupt directly the file on which you write (since there is no locking of the file and the write all write together).

For the sake of simplicity and readability I gave up on Async and went full sync. Sure there is a downside in performance, this is why I added the possibility to not save on the file at each push but when the user decides (leading to a possible loss of data in case of power loss).

If you want to go for Async I/O, I'll advise to use a lock like this lib: https://www.npmjs.com/package/rwlock 
to be able to block access to the file and do one writing at a time.
