### ISSUE TITLE
"DatabaseError: Can't Load Database" when push() immediately follows a database creation for non-existing file

### ISSUE THREAD

**Issue by vihanp** [Belphemur/node-json-db#6]
Timing issue?
Env:
Node: v4.1.1, Windows 7
node-json-db: 0.4.6

To reproduce: run 
```javascript
var JsonDB = require('node-json-db');
var db = new JsonDB("myDataBase", true, false);
db.push("/test1","super test");
```
while the file "myDatabase.json" does not exists.
DatabaseError is thrown.

Work-around is to create myDataBase.json with empty json, then it works.

Would this be a cause?
on initial database save, mkdirp is called  which is async

**Comment by Belphemur** [comment]
When you create the JsonDB object, the lib will create the file if it doesn't exists and should log: **"[JsonDB] DataBase " + self.filename + " created."**

In fact, I'm quite sure the program you launch that use the library doesn't have the right to write in the current directory.

Try with a path like /tmp/myDb or any other path that you're sure your program can write to.

**Comment by HowardPautz** [comment]
Might be an async bug after all. I'm getting the same error as @vihanp on both a Mac OSX and a linux (Ubuntu) box.

My node / npm install is fresh and clean.
I have full rights to install and code directories, so 
installed as:
```
npm install node-json-db --save
```
I just copied and pasted the first three lines of code from the first example:

```
var JsonDB = require('node-json-db');
var db = new JsonDB("myDataBase", true, false);
db.push("/test1","super test");
```
saved as ```foobar.js```
running ```node foobar.js```

results in
```
~/0-JS-tests/node_modules/node-json-db/JsonDB.js:204

            throw error;
            ^
NestedError: Can't Load Database
    at DatabaseError.Error (native)
    at DatabaseError.NestedError (~/0-JS-tests/node_modules/node-json-db/lib/Errors.js:7:25)
    at new DatabaseError (~/0-JS-tests/node_modules/node-json-db/lib/Errors.js:29:33)
    at JsonDB.load (~/0-JS-tests/node_modules/node-json-db/JsonDB.js:202:25)
    at JsonDB._getData (~/0-JS-tests/node_modules/node-json-db/JsonDB.js:74:14)
    at JsonDB._getParentData (~/0-JS-tests/node_modules/node-json-db/JsonDB.js:60:44)
    at JsonDB.push (~/0-JS-tests/node_modules/node-json-db/JsonDB.js:142:27)
    at Object.<anonymous> (~/0-JS-tests/node-json-db/foobar.js:10:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```
commenting out the third line
// db.push("/test1","super test");
and running again, creates the DB --- and then the samples work.

I also tried to create an empty DB before running the three lines uncommented, by doing merely:
``` echo > myDataBase.json```
but the initial push() still failed with same error.

Besides confirming the bug, I wonder if @vihanp is on to something here - that there is some kind of async error here.  The reason is that I can get the same error on the *second* push (), when the first push() worked.

thanks for your efforts - this is a nice idea!

- H

**Comment by Belphemur** [comment]
You are both right... Sorry @vihanp 
I'm using mkdirp to create directory that are set in the path of the database, for an unknown reason I didn't use the sync version of it, which lead to this bug. I reproduced, tested and corrected it.

I'll release the new version soon. Thanks.
